spring.application.name=online-mart-platform

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/online_mart
spring.datasource.username=postgres
spring.datasource.password=Satheesh@5008

# Connection Pool (HikariCP is default in Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true