server.port=8084
spring.application.name=customer-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/online_mart}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Satheesh@5008}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces
management.tracing.sampling.probability=1.0

logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]