server.port=8082
spring.application.name=order-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/online_mart}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Satheesh@5008}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cloud.openfeign.lazy-attributes-resolution=true

# Feign target URLs
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
cart.service.url=${CART_SERVICE_URL:http://localhost:8083}

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic.order.created=local.sales.ecommerce.order.created.v1
spring.kafka.topic.order.cancelled=local.sales.ecommerce.order.cancelled.v1
spring.kafka.topic.inventory.reserved=local.sales.ecommerce.inventory.reserved.v1
spring.kafka.topic.inventory.failed=local.sales.ecommerce.inventory.failed.v1

# Kafka Consumer
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
